#!/bin/bash
# This script duplicates the last line of the file iacta.

# Get the last line of the file and store it in a variable
last_line=$(tail -n 1 iacta)

# Append the last line to the end of the file
echo "$last_line" >> iacta

echo "Last line duplicated."
